import { NextRequest, NextResponse } from 'next/server';
import { buildFallback } from '@/lib/fallback-config';
import { parseGameConfigExtended } from '@/lib/game-config-schema';
import { badRequest, logApiError } from '@/lib/api-errors';

const LM_BASE_URL = process.env.QWEN_BASE_URL || 'http://localhost:1234';
const LM_MODEL = process.env.QWEN_MODEL || 'qwen3-coder-30b-a3b-instruct-mlx';

const MAX_DREAM_LENGTH = 5000;
const LLM_TIMEOUT_MS = Number(process.env.LLM_TIMEOUT_MS) || 60000;
const LLM_MAX_TOKENS = 1500;

const SYSTEM_PROMPT = `You are DreamCraft AI — a cinematic dream-to-game director who turns
a single dream description into a complete miniature world. Every word you choose
materializes on screen: a narrative read aloud in 3D space, a color palette painted
across platforms and skies, a character mesh generated by a separate model from
your description.

Your job is to LISTEN to the dream and amplify it. Do not normalize it into a
generic fantasy template. If the dream is industrial, the world is metallic.
If the dream is grief, the world is dim and slow. If the dream is absurd, the
world bends physics. Stay loyal to the dreamer's voice.

# Field-by-field direction

mood — pick the closest match. Use the dream's emotional core, not just keywords.
  surreal_calm: dreamlike, soft, drifting, no clear threat
  dark_fantasy: medieval menace, cursed beauty, knights and demons
  cozy_dream: warm, safe, plants and small creatures, sunset light
  nightmare: visceral fear, body horror, pursuit, blood-tones
  cyber_dream: neon, circuits, glitch, holograms, dystopian tech
  ethereal: weightless, glass, silver, ghostly, lullaby quality
  whimsical: playful, candy, balloons, friendly absurdity
  cosmic: outer space, stars, void, scale beyond human

style — surface aesthetic. surreal | dark | cozy | nightmare | cyberpunk |
watercolor | cosmic.

main_character.description — 6-12 words describing the protagonist as a physical
3D object that another model will sculpt from your text. Mention silhouette,
material, posture, key feature. Examples: "a hooded figure made of folded
black paper, sharp angles" / "a chubby moss-covered turtle with glowing
mushroom shell" / "a winged shard of obsidian glass, no body, just blades".
main_character.color — emissive accent. Reads against the sky.

background.sky_color — the dominant zenith tone the dreamer sees.
background.ground_color — what the terrain rests on.

color_palette — exactly 4 hex colors with semantic roles:
  [0] character / hero accent (pairs with main_character.color)
  [1] mid-tone — platforms, light wash
  [2] deep — shadows, lower-thirds
  [3] near-black or near-white anchor
The four colors should look intentional together, not random. Think movie
poster, not party balloons.

narrative — 2-3 sentences, 30-60 words total. Vivid, sensory, present-tense.
This text floats over the spawn platform AND appears in the side panel.
Include at least one specific image from the dream (a phrase, an object, a
verb). Do NOT summarize the dream — extend it. Examples of the right register:
  "Glass butterflies pulse with the memory of your name. The wind tastes
  like a lullaby someone forgot to finish, and the path ahead glitters with
  the bones of unfinished thoughts."
  "Towering spires hum with dormant power. Shadows lean from every doorway,
  drinking the light, while something patient waits at the corridor's end."

goal — 5-10 word win condition, poetic command. "Reach the heart of the
nebula" / "Wake before the corridor closes" / "Bind the wandering moon".

music_prompt — 10-16 words. Genre + BPM + 2-3 instruments + emotion.
"Dark ambient, 55 BPM, drone bass and distant choir, slow grief, no drums."
"Synthwave, 128 BPM, analog leads and gated drums, urgent and neon-lit."

platforms — integer 5-12. More for sprawling dreams, fewer for tight ones.
enemy_count — integer 0-8. 0 for peaceful, 4-6 for threat-driven, 8 only
when the dream is overtly hostile.

Return ONLY valid JSON. No markdown fences. No commentary. No <think> tags.`;

interface LLMChatResponse {
  choices?: Array<{ message?: { content?: string } }>;
}

export async function POST(req: NextRequest) {
  // -------------------------------------------------------------------------
  // Phase 5: request validation
  // -------------------------------------------------------------------------

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return badRequest('Invalid JSON body');
  }

  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return badRequest('Field "dream" is required and must be a string', { field: 'dream' });
  }

  const rawDream = (body as Record<string, unknown>).dream;
  if (typeof rawDream !== 'string') {
    return badRequest('Field "dream" is required and must be a string', { field: 'dream' });
  }

  const dream = rawDream.trim();
  if (dream.length === 0) {
    return badRequest('Dream cannot be empty', { field: 'dream' });
  }

  if (dream.length > MAX_DREAM_LENGTH) {
    return badRequest('Dream exceeds 5000 characters', {
      field: 'dream',
      max: MAX_DREAM_LENGTH,
      actual: dream.length,
    });
  }

  // -------------------------------------------------------------------------
  // Phase 2: LLM call + response normalization with graceful fallback
  // -------------------------------------------------------------------------

  try {
    const res = await fetch(`${LM_BASE_URL}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: LM_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          {
            role: 'user',
            content: `The dreamer wrote:\n\n"${dream}"\n\nTreat them as the protagonist. Build the world they were in: setting, atmosphere, what pursues them or what awaits them, what their salvation looks like. Stay loyal to specific images and verbs they used. Generate the JSON now. /no_think`,
          },
        ],
        temperature: 0.7,
        max_tokens: LLM_MAX_TOKENS,
        stream: false,
        response_format: {
          type: 'json_schema',
          json_schema: {
            name: 'game_config',
            strict: true,
            schema: {
              type: 'object',
              additionalProperties: false,
              required: [
                'mood', 'style', 'genre',
                'main_character', 'background', 'color_palette',
                'narrative', 'goal', 'music_prompt',
                'platforms', 'enemy_count',
              ],
              properties: {
                mood: { type: 'string', enum: ['surreal_calm','dark_fantasy','cozy_dream','nightmare','cyber_dream','ethereal','whimsical','cosmic'] },
                style: { type: 'string', enum: ['surreal','dark','cozy','nightmare','cyberpunk','watercolor','cosmic'] },
                genre: { type: 'string', const: '3d_platformer' },
                main_character: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['description', 'color'],
                  properties: {
                    description: { type: 'string' },
                    color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' },
                  },
                },
                background: {
                  type: 'object',
                  additionalProperties: false,
                  required: ['sky_color', 'ground_color'],
                  properties: {
                    sky_color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' },
                    ground_color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' },
                  },
                },
                color_palette: {
                  type: 'array',
                  minItems: 4, maxItems: 4,
                  items: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' },
                },
                narrative: { type: 'string' },
                goal: { type: 'string' },
                music_prompt: { type: 'string' },
                platforms: { type: 'integer', minimum: 5, maximum: 12 },
                enemy_count: { type: 'integer', minimum: 0, maximum: 8 },
              },
            },
          },
        },
        chat_template_kwargs: { enable_thinking: false },
      }),
      signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`LM Studio error ${res.status}: ${errText}`);
    }

    const data = (await res.json()) as LLMChatResponse;
    const rawContent: string = data.choices?.[0]?.message?.content ?? '';

    let rawObj: unknown;
    try {
      rawObj = parseJsonFromLLM(rawContent);
    } catch (parseErr) {
      console.error('[analyze] JSON parse failed; raw content was:\n---\n%s\n---', rawContent.slice(0, 2000));
      throw parseErr;
    }
    const normalized = parseGameConfigExtended(rawObj, dream);
    return NextResponse.json(normalized, { status: 200 });
  } catch (err) {
    logApiError('analyze', err);
    // Graceful degradation: never crash the demo. `buildFallback` is canonical
    // and trusted, so no further normalization is required.
    return NextResponse.json(buildFallback(dream), { status: 200 });
  }
}

/**
 * Extract a JSON object from an LLM response string.
 *
 * Defense-in-depth: strips `<think>...</think>` blocks and markdown fences
 * even though the SYSTEM_PROMPT forbids them, then slices from the first `{`
 * to the last `}` and runs `JSON.parse`. May throw — callers must handle it.
 */
function parseJsonFromLLM(text: string): unknown {
  const noThink = text.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
  const cleaned = noThink.replace(/```json?\n?/g, '').replace(/```/g, '').trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start === -1 || end === -1) throw new Error('No JSON found in LLM response');
  return JSON.parse(cleaned.slice(start, end + 1));
}
