// Shared shape for generated assets that flow from the two asset routes
// (/api/generate-3d and /api/generate-assets) into the client.
//
// The two routes both return a property called `character_url` — one is a 2D
// PNG sprite, the other is a 3D GLB. To avoid collisions when merging the
// responses, the client remaps them into the disambiguated keys below before
// storing in `localStorage.gameAssets`.

/**
 * Generated-asset URLs for a single dream session.
 * Every URL is either a public path under `/generated/<id>/` or
 * `/generated3d/<id>/`, OR `null` when generation was skipped/failed.
 *
 * The downstream consumer (DreamGame3D) must tolerate every field being null —
 * procedural rendering is always available as a fallback.
 */
export interface GameAssets {
  /** 2D PNG generated by Stable Diffusion (Phase 6: optional / decorative). */
  background_2d: string | null;
  character_2d:  string | null;
  platform_2d:   string | null;
  /** 3D GLB generated by TRELLIS (Phase 3: optional / decorative). */
  character_3d:  string | null;
  prop_3d:       string | null;
  portal_3d:     string | null;
  /** 3D OBJ generated by LLaMA-Mesh (local, free, low-poly). Loaded as
   *  player character when TRELLIS GLB is absent. */
  character_obj: string | null;
  /** Echoed back so the client can correlate to the per-generation directory. */
  generationId?: string;
  /** True when at least one URL above is non-null. Convenience flag for UI. */
  hasAny: boolean;
}

/** Empty/initial assets — useful for the procedural-only render path. */
export const NO_ASSETS: GameAssets = {
  background_2d: null,
  character_2d:  null,
  platform_2d:   null,
  character_3d:  null,
  prop_3d:       null,
  portal_3d:     null,
  character_obj: null,
  hasAny: false,
};

/**
 * Custom DOM event name dispatched by /loading-dream when fire-and-forget
 * asset generation lands in `localStorage.gameAssets`. /play listens for
 * this on `window` to pick up assets that arrived AFTER navigation.
 *
 * `storage` events also work for the multi-tab case but do NOT fire in the
 * same tab that wrote the value — hence the custom event.
 */
export const DREAM_ASSETS_UPDATED_EVENT = 'dreamAssetsUpdated';

/** Type guard — accepts a value parsed from localStorage and validates it. */
export function isGameAssets(v: unknown): v is GameAssets {
  if (!v || typeof v !== 'object') return false;
  const o = v as Record<string, unknown>;
  const urlOrNull = (x: unknown): boolean =>
    x === null || (typeof x === 'string' && x.length > 0 && x.length < 512);
  return (
    urlOrNull(o.background_2d) &&
    urlOrNull(o.character_2d) &&
    urlOrNull(o.platform_2d) &&
    urlOrNull(o.character_3d) &&
    urlOrNull(o.prop_3d) &&
    urlOrNull(o.portal_3d) &&
    // character_obj is optional in old persisted snapshots — accept missing.
    (o.character_obj === undefined || urlOrNull(o.character_obj)) &&
    typeof o.hasAny === 'boolean'
  );
}

/**
 * Merge the raw responses from /api/generate-assets (2D) and
 * /api/generate-3d (3D) into the disambiguated client shape.
 * Both inputs are `unknown` because they come from `fetch().json()`.
 */
export function mergeAssetResponses(
  twoD: unknown,
  threeD: unknown,
  generationId?: string,
  mesh?: unknown,
): GameAssets {
  const two = (twoD && typeof twoD === 'object' ? twoD : {}) as Record<string, unknown>;
  const three = (threeD && typeof threeD === 'object' ? threeD : {}) as Record<string, unknown>;
  const meshObj = (mesh && typeof mesh === 'object' ? mesh : {}) as Record<string, unknown>;
  const url = (v: unknown): string | null =>
    typeof v === 'string' && v.length > 0 && v.length < 512 ? v : null;

  const out: GameAssets = {
    background_2d: url(two.background_url),
    character_2d:  url(two.character_url),
    platform_2d:   url(two.platform_url),
    character_3d:  url(three.character_url),
    prop_3d:       url(three.prop_url),
    portal_3d:     url(three.portal_url),
    character_obj: url(meshObj.character_obj_url),
    generationId,
    hasAny: false,
  };
  out.hasAny =
    !!out.background_2d ||
    !!out.character_2d ||
    !!out.platform_2d ||
    !!out.character_3d ||
    !!out.prop_3d ||
    !!out.portal_3d ||
    !!out.character_obj;
  return out;
}
